const countries = [
  {
    name: "Norway",
    continent: "Europe",
    capital: "Oslo",
    population: 5400000,
    isLandlocked: false,
    flag: "🇳🇴",
  },
  {
    name: "Nepal",
    continent: "Asia",
    capital: "Kathmandu",
    population: 30030000,
    isLandlocked: true,
    flag: "🇳🇵",
  },
  {
    name: "Niger",
    continent: "Africa",
    capital: "Niamey",
    population: 25100000,
    isLandlocked: true,
    flag: "🇳🇪",
  },
  {
    name: "Netherlands",
    continent: "Europe",
    capital: "Amsterdam",
    population: 17400000,
    isLandlocked: false,
    flag: "🇳🇱",
  },
  {
    name: "South Korea",
    continent: "Asia",
    capital: "Seoul",
    population: 51780000,
    isLandlocked: false,
    flag: "🇰🇷",
  },
  {
    name: "South Africa",
    continent: "Africa",
    capital: "Pretoria",
    population: 60040000,
    isLandlocked: false,
    flag: "🇿🇦",
  },
  {
    name: "Sweden",
    continent: "Europe",
    capital: "Stockholm",
    population: 10400000,
    isLandlocked: false,
    flag: "🇸🇪",
  },
  {
    name: "Spain",
    continent: "Europe",
    capital: "Madrid",
    population: 47350000,
    isLandlocked: false,
    flag: "🇪🇸",
  },
  {
    name: "India",
    continent: "Asia",
    capital: "New Delhi",
    population: 1393000000,
    isLandlocked: false,
    flag: "🇮🇳",
  },
  {
    name: "Indonesia",
    continent: "Asia",
    capital: "Jakarta",
    population: 273500000,
    isLandlocked: false,
    flag: "🇮🇩",
  },
  {
    name: "Iceland",
    continent: "Europe",
    capital: "Reykjavik",
    population: 366000,
    isLandlocked: false,
    flag: "🇮🇸",
  },
  {
    name: "Iran",
    continent: "Asia",
    capital: "Tehran",
    population: 84900000,
    isLandlocked: false,
    flag: "🇮🇷",
  },
  {
    name: "Russia",
    continent: "Europe/Asia",
    capital: "Moscow",
    population: 145900000,
    isLandlocked: false,
    flag: "🇷🇺",
  },
  {
    name: "Romania",
    continent: "Europe",
    capital: "Bucharest",
    population: 19000000,
    isLandlocked: false,
    flag: "🇷🇴",
  },
  {
    name: "Portugal",
    continent: "Europe",
    capital: "Lisbon",
    population: 10200000,
    isLandlocked: false,
    flag: "🇵🇹",
  },
];
